# Site settings
author: Aidan
title: Aidan
description: Aidan's personal website
logo: favicon.png
url: http://localhost:3000

search: true
comments: true

# discus_shortname: Aidan
duoshuo_shortname: aidandai

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: true

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200

# Owner/author information
owner:
  name: Aidan
  #email: webaidandai@gmail.com
  #avatar: avatar.jpg
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description: Front-end Engineer

# Social networking links used in footer. Update and remove as you like.
github_username: AidanDai
weibo_username: webAidan
zhihu_username: Aidan
segmentfault_username: Aidan
twitter_username: AidanDai

# Internal nav
nav:
  blog: "/blog/"
  code: "/code/"
  like: "/like/"
  about: "/about/"
  wiki: "/wiki/"
  resume: "/resume/"

router:
  category: "/blog/category.html"
  tag: "/blog/tag.html"
  author: "/blog/author.html"
  archive: "/blog/archive.html"

permalink: "/posts/:title.html"

paginate: 10
paginate_path: "/blog/page:num"

# Server
destination:      	 ./_site
port:             	 4000

# Build settings
# highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge
  # coderay:
  #   coderay_line_numbers: inline
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 2
  #   coderay_bold_every: 10
  #   coderay_css: style
  # extensions:
  #   - autolink
  #   - footnotes
  #   - smart
  #   - tables


# highlighter:        rb-pygments
# markdown:           redcarpet
# redcarpet:
#   extensions:     
#    - Hard_wrap
#    - no_intra_emphasis
#    - strikethrough
#    - fenced_code_blocks
#    - autolink
#    - tables
#    - with_toc_data
#    - highlight
#    - footnotes
  # input:          GFM

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-xxxxxxxx-x
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

gems: [jekyll-paginate]

exclude: [node_modules, gulpfile.js]